version: '3'
services:
  api:
    container_name: cyborg-container
    build: .
    entrypoint: npm run start
    env_file:
      - .env
    ports:
      - '8080:8080'

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
